### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by luocha0107** [ga1i13o/mcloc_poseref#3]
Traceback (most recent call last):
  File "/root/data_user/ysl/mcloc_poseref/refine_pose.py", line 241, in <module>
    main(args)
  File "/root/data_user/ysl/mcloc_poseref/refine_pose.py", line 42, in main
    scores_temp, render_dir = refinement_loop(args)
  File "/root/data_user/ysl/mcloc_poseref/refine_pose.py", line 78, in refinement_loop
    renderer = get_renderer(args, paths_conf)
  File "/root/data_user/ysl/mcloc_poseref/gloc/rendering/rend_conf.py", line 33, in get_renderer
    from gloc.rendering.splatting_renderer import GaussianSplattingRenderer
  File "/root/data_user/ysl/mcloc_poseref/gloc/rendering/splatting_renderer.py", line 21, in <module>
    from gaussian_renderer import render
ModuleNotFoundError: No module named 'gaussian_renderer'

**Comment by ga1i13o** [comment]
hello, there was a small issue in how I had setup the submodules, it is now fixed
make sure to clone the repo with the `--recursive` option
